const fs = require('fs');
const filePath = 'C:/Users/CORE ULTRA/Desktop/empiria-backend/public/app.js';
const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

console.log('Total lines before:', lines.length);
console.log('Line 1226 (should be _initDashboardCharts):', lines[1225].trim().slice(0,50));
console.log('Line 1400 (should be loadDashboardModule):', lines[1399].trim().slice(0,50));
console.log('Line 1566 (should be }):', lines[1565].trim());

const newInitCharts = [
"async function _initDashboardCharts(payload) {",
"  await loadChartJs();",
"  const Chart = window.Chart;",
"  if (!Chart) return;",
"",
"  for (const c of Object.values(_dbCharts)) { try { c.destroy(); } catch {} }",
"  _dbCharts = {};",
"",
"  const kpis   = payload.kpis || {};",
"  const covMun = payload.coverageByMunicipality || {};",
"",
"  // TC/MT contratado vs requerido por municipio (grouped bar)",
"  const tcmtCanvas = document.getElementById(\"db2-chart-tcmt\");",
"  if (tcmtCanvas) {",
"    const munEntries = Object.entries(covMun)",
"      .filter(([, cv]) => (cv.requiredTc + cv.requiredMt) > 0)",
"      .sort((a, b) => (b[1].requiredTc + b[1].requiredMt) - (a[1].requiredTc + a[1].requiredMt))",
"      .slice(0, 10);",
"    _dbCharts.tcmt = new Chart(tcmtCanvas, {",
"      type: \"bar\",",
"      data: {",
"        labels: munEntries.map(([m]) => m),",
"        datasets: [",
"          { label: \"TC Requerido\",   data: munEntries.map(([, cv]) => cv.requiredTc),   backgroundColor: \"#3b82f633\", borderColor: \"#3b82f6\", borderWidth: 1, borderRadius: 3 },",
"          { label: \"TC Contratado\",  data: munEntries.map(([, cv]) => cv.contractedTc), backgroundColor: \"#3b82f6cc\", borderColor: \"#3b82f6\", borderWidth: 1, borderRadius: 3 },",
"          { label: \"MT Requerido\",   data: munEntries.map(([, cv]) => cv.requiredMt),   backgroundColor: \"#f59e0b33\", borderColor: \"#f59e0b\", borderWidth: 1, borderRadius: 3 },",
"          { label: \"MT Contratado\",  data: munEntries.map(([, cv]) => cv.contractedMt), backgroundColor: \"#f59e0bcc\", borderColor: \"#f59e0b\", borderWidth: 1, borderRadius: 3 },",
"        ],",
"      },",
"      options: {",
"        responsive: true, maintainAspectRatio: false,",
"        plugins: { legend: { position: \"bottom\", labels: { font: { size: 11 }, padding: 10, boxWidth: 12 } } },",
"        scales: {",
"          x: { ticks: { font: { size: 10 } }, grid: { display: false } },",
"          y: { beginAtZero: true, grid: { color: \"#f1f5f9\" }, ticks: { font: { size: 11 }, precision: 0 } },",
"        },",
"      },",
"    });",
"  }",
"",
"  // Género (doughnut)",
"  const genderCanvas = document.getElementById(\"db2-chart-gender\");",
"  if (genderCanvas) {",
"    _dbCharts.gender = new Chart(genderCanvas, {",
"      type: \"doughnut\",",
"      data: {",
"        labels: [\"Mujeres TC\", \"Mujeres MT\", \"Hombres TC\", \"Hombres MT\"],",
"        datasets: [{",
"          data: [kpis.femaleTc||0, kpis.femaleMt||0, kpis.maleTc||0, kpis.maleMt||0],",
"          backgroundColor: [\"#ec4899cc\", \"#f9a8d4cc\", \"#3b82f6cc\", \"#93c5fdcc\"],",
"          borderColor: [\"#ec4899\", \"#f9a8d4\", \"#3b82f6\", \"#93c5fd\"],",
"          borderWidth: 2,",
"        }],",
"      },",
"      options: {",
"        responsive: true, maintainAspectRatio: false, cutout: \"62%\",",
"        plugins: {",
"          legend: { position: \"bottom\", labels: { font: { size: 11 }, padding: 10, boxWidth: 12 } },",
"          tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${ctx.parsed}` } },",
"        },",
"      },",
"    });",
"  }",
"",
"  // Tipos de contrato (bar)",
"  const contractCanvas = document.getElementById(\"db2-chart-contracts\");",
"  if (contractCanvas) {",
"    _dbCharts.contracts = new Chart(contractCanvas, {",
"      type: \"bar\",",
"      data: {",
"        labels: [\"Obra o Labor\", \"Término Fijo\"],",
"        datasets: [{",
"          label: \"Contratos\",",
"          data: [kpis.ctObraLabor||0, kpis.ctTerminoFijo||0],",
"          backgroundColor: [\"#8b5cf6cc\", \"#06b6d4cc\"],",
"          borderColor: [\"#8b5cf6\", \"#06b6d4\"],",
"          borderWidth: 1, borderRadius: 6,",
"        }],",
"      },",
"      options: {",
"        responsive: true, maintainAspectRatio: false,",
"        plugins: {",
"          legend: { display: false },",
"          tooltip: { callbacks: { label: ctx => ` ${ctx.parsed.y} contratos` } },",
"        },",
"        scales: {",
"          y: { beginAtZero: true, grid: { color: \"#f1f5f9\" }, ticks: { font: { size: 12 }, precision: 0 } },",
"          x: { ticks: { font: { size: 13, weight: \"600\" } }, grid: { display: false } },",
"        },",
"      },",
"    });",
"  }",
"}"
].join('\r\n');

const newLoadDashboard = [
"async function loadDashboardModule() {",
"  _clearDashboardTimers();",
"",
"  const payload = await apiFetch(\"/dashboard-summary\");",
"  const kpis = payload.kpis || {};",
"",
"  const html = `",
"<div class=\"db2-wrap\">",
"",
"  <!-- Fila 1: TC / MT + 20% + Total personal + Retiros -->",
"  <div class=\"db2-kpi-row\">",
"    <div class=\"db2-kpi-card db2-kpi-accent-green\">",
"      <div class=\"db2-kpi-label\">TC Contratado / Requerido</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-tc\">${kpis.contractedTc||0} / ${kpis.requiredTc||0}</div>",
"      <div class=\"db2-prog-wrap\" style=\"margin:6px 0\"><div class=\"db2-prog-bar\" id=\"db2-prog-tc\" style=\"width:${Math.min(kpis.pctTc??0,100)}%;background:${coverageColor(kpis.pctTc)}\"></div></div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-tc\">${kpis.pctTc != null ? kpis.pctTc + \"% completado\" : \"Sin datos de cobertura\"}</div>",
"    </div>",
"    <div class=\"db2-kpi-card db2-kpi-accent-amber\">",
"      <div class=\"db2-kpi-label\">MT Contratado / Requerido</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-mt\">${kpis.contractedMt||0} / ${kpis.requiredMt||0}</div>",
"      <div class=\"db2-prog-wrap\" style=\"margin:6px 0\"><div class=\"db2-prog-bar\" id=\"db2-prog-mt\" style=\"width:${Math.min(kpis.pctMt??0,100)}%;background:${coverageColor(kpis.pctMt)}\"></div></div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-mt\">${kpis.pctMt != null ? kpis.pctMt + \"% completado\" : \"Sin datos de cobertura\"}</div>",
"    </div>",
"    <div class=\"db2-kpi-card db2-kpi-accent-blue\">",
"      <div class=\"db2-kpi-label\">20% TC Requerido</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-pct20\">${kpis.tcPct20||0}</div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-pct20\">20% de ${kpis.requiredTc||0} TC requeridos</div>",
"    </div>",
"    <div class=\"db2-kpi-card db2-kpi-accent-blue\">",
"      <div class=\"db2-kpi-label\">Total Personal</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-total\">${kpis.totalPersonnel||0}</div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-total\">${kpis.activePersonnel||0} activos — ${kpis.inactivePersonnel||0} inactivos</div>",
"    </div>",
"    <div class=\"db2-kpi-card db2-kpi-accent-red\">",
"      <div class=\"db2-kpi-label\">Retiros este año</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-retiros\">${kpis.retirosThisYear||0}</div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-retiros\">${kpis.retirosPct||0}% del total · ${new Date().getFullYear()}</div>",
"    </div>",
"  </div>",
"",
"  <!-- Fila 2: Género + Contratos -->",
"  <div class=\"db2-kpi-row\">",
"    <div class=\"db2-kpi-card\" style=\"border-top:3px solid #ec4899\">",
"      <div class=\"db2-kpi-label\">♀ Mujeres</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-female\" style=\"color:#ec4899\">${kpis.femaleCount||0}</div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-female\">TC: ${kpis.femaleTc||0} · MT: ${kpis.femaleMt||0}</div>",
"    </div>",
"    <div class=\"db2-kpi-card\" style=\"border-top:3px solid #3b82f6\">",
"      <div class=\"db2-kpi-label\">♂ Hombres</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-male\" style=\"color:#3b82f6\">${kpis.maleCount||0}</div>",
"      <div class=\"db2-kpi-sub\" id=\"db2-sub-male\">TC: ${kpis.maleTc||0} · MT: ${kpis.maleMt||0}</div>",
"    </div>",
"    <div class=\"db2-kpi-card\" style=\"border-top:3px solid #8b5cf6\">",
"      <div class=\"db2-kpi-label\">Contratos Obra o Labor</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-obra\" style=\"color:#8b5cf6\">${kpis.ctObraLabor||0}</div>",
"      <div class=\"db2-kpi-sub\">contratos activos</div>",
"    </div>",
"    <div class=\"db2-kpi-card\" style=\"border-top:3px solid #06b6d4\">",
"      <div class=\"db2-kpi-label\">Contratos Término Fijo</div>",
"      <div class=\"db2-kpi-value\" id=\"db2-v-fijo\" style=\"color:#06b6d4\">${kpis.ctTerminoFijo||0}</div>",
"      <div class=\"db2-kpi-sub\">contratos activos</div>",
"    </div>",
"  </div>",
"",
"  <!-- Charts: TC/MT por municipio + Género -->",
"  <div class=\"db2-charts-row\">",
"    <div class=\"db2-chart-card db2-chart-wide\">",
"      <div class=\"db2-card-header\">TC / MT Contratado vs Requerido por Municipio</div>",
"      <div class=\"db2-chart-area\" style=\"height:300px\"><canvas id=\"db2-chart-tcmt\"></canvas></div>",
"    </div>",
"    <div class=\"db2-chart-card\">",
"      <div class=\"db2-card-header\">Distribución de Género</div>",
"      <div class=\"db2-chart-area\" style=\"height:300px\"><canvas id=\"db2-chart-gender\"></canvas></div>",
"    </div>",
"  </div>",
"",
"  <!-- Charts: Tipos contrato + Edad por cargo -->",
"  <div class=\"db2-charts-row\">",
"    <div class=\"db2-chart-card\">",
"      <div class=\"db2-card-header\">Tipos de Contrato</div>",
"      <div class=\"db2-chart-area\" style=\"height:220px\"><canvas id=\"db2-chart-contracts\"></canvas></div>",
"    </div>",
"    <div class=\"db2-chart-card db2-chart-wide\">",
"      <div class=\"db2-card-header\">Edad del Personal por Cargo</div>",
"      <div style=\"overflow-x:auto\">",
"        <table class=\"db2-table\">",
"          <thead id=\"db2-age-thead\"></thead>",
"          <tbody id=\"db2-age-table-body\"></tbody>",
"        </table>",
"      </div>",
"    </div>",
"  </div>",
"",
"  <div class=\"db2-refresh-note\">",
"    Última actualización: <span id=\"db2-last-update\">${new Date().toLocaleTimeString(\"es-CO\")}</span>",
"    &nbsp;•&nbsp; Actualización automática cada 60 s",
"  </div>",
"",
"</div>`;",
"",
"  setTimeout(async () => {",
"    _renderDashboardKpis(kpis);",
"    _renderAgeTable(payload.ageByPosition || {}, payload.ageBrackets || []);",
"    await _initDashboardCharts(payload);",
"",
"    _dbRefreshTimer = setInterval(async () => {",
"      try {",
"        const fresh = await apiFetch(\"/dashboard-summary\");",
"        const fk = fresh.kpis || {};",
"        _renderDashboardKpis(fk);",
"        _renderAgeTable(fresh.ageByPosition || {}, fresh.ageBrackets || []);",
"",
"        if (_dbCharts.tcmt) {",
"          const covMun = fresh.coverageByMunicipality || {};",
"          const munEntries = Object.entries(covMun)",
"            .filter(([, cv]) => (cv.requiredTc + cv.requiredMt) > 0)",
"            .sort((a, b) => (b[1].requiredTc + b[1].requiredMt) - (a[1].requiredTc + a[1].requiredMt))",
"            .slice(0, 10);",
"          _dbCharts.tcmt.data.labels = munEntries.map(([m]) => m);",
"          _dbCharts.tcmt.data.datasets[0].data = munEntries.map(([, cv]) => cv.requiredTc);",
"          _dbCharts.tcmt.data.datasets[1].data = munEntries.map(([, cv]) => cv.contractedTc);",
"          _dbCharts.tcmt.data.datasets[2].data = munEntries.map(([, cv]) => cv.requiredMt);",
"          _dbCharts.tcmt.data.datasets[3].data = munEntries.map(([, cv]) => cv.contractedMt);",
"          _dbCharts.tcmt.update(\"none\");",
"        }",
"        if (_dbCharts.gender) {",
"          _dbCharts.gender.data.datasets[0].data = [fk.femaleTc||0, fk.femaleMt||0, fk.maleTc||0, fk.maleMt||0];",
"          _dbCharts.gender.update(\"none\");",
"        }",
"        if (_dbCharts.contracts) {",
"          _dbCharts.contracts.data.datasets[0].data = [fk.ctObraLabor||0, fk.ctTerminoFijo||0];",
"          _dbCharts.contracts.update(\"none\");",
"        }",
"",
"        const tsEl = document.getElementById(\"db2-last-update\");",
"        if (tsEl) tsEl.textContent = new Date().toLocaleTimeString(\"es-CO\");",
"      } catch { /* silent refresh failure */ }",
"    }, 60000);",
"  }, 80);",
"",
"  return html;",
"}"
].join('\r\n');

// lines 0..1224 = before _initDashboardCharts
// lines 1225..1397 = old _initDashboardCharts  (replace)
// line 1398 = blank line
// lines 1399..1565 = old loadDashboardModule   (replace)
// lines 1566..end = rest of file

const before = lines.slice(0, 1225);
const blankLine = [''];
const after = lines.slice(1566);

const newLines = [
  ...before,
  ...newInitCharts.split('\r\n'),
  ...blankLine,
  ...newLoadDashboard.split('\r\n'),
  ...after
];

const newContent = newLines.join('\n');
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Done. New total lines:', newContent.split('\n').length);
